server:
  port: 8888

spring:
  application:
    name: my-gateway
  cloud:
    gateway:
      routes:
        - id: sty-route
          uri: http://127.0.0.1:10000/css
          predicates:
            - Path=/css/**
        - id: lgm-route
          uri: lb://stu-lgm              # http://127.0.0.1:10000/lgm
          predicates:
            - Path=/lgm/**
        - id: pdl-route
          uri: lb://pdl-cloud              #http://127.0.0.1:11000/pdl
          predicates:
            - Path=/pdl/**
        - id: sty-route
          uri: lb://yfq-cloud
          predicates:
            - Path=/yfq/**
        - id: sty-route
          uri: lb://dept-zgr
          predicates:
            - Path=/zgr/**
        - id: sty-route
          uri: lb://provider-zxc
          predicates:
            - Path=/grade/**
        - id: sty-route
          uri: lb://zsw-pj
          predicates:
            - Path=/zsw/**