server:
  port: 8888


spring:
  cloud:
    gateway:
      routes:
        - id: lgm-route
          uri: lb://stu-lgm
          predicates:
            - Path=/lgm/**
        - id: pdl-route
          uri: lb://pdl-cloud
          predicates:
            - Path=/pdl/**