server:
  port: 6003
spring:
  application:
    name: exam-wjf
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/clouddemo?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: provider.model
  configuration:
    map-underscore-to-camel-case: true

 cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#eureka:
  #client:
    #service-url:
      #defaultZone: http://localhost:6001/eureka
      # Eureka服务注册中心会将自己作为客户端来尝试注册它自己，必須禁止,则不会在eurekaserver中显示注册
    #register-with-eureka: false
    #fetch-registry: false
    #instance:
      #prefer-ip-address: true
      #instance-id: status-provider1



info:
  app.name: provider
  author: wjf
