server:
  port: 6003
spring:
  application:
    name: exam-wjf
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/clouddemo?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  autoconfigure:
    exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: provider.model  # 注意：对应实体类的路径






#eureka:
  #client:
    #service-url:
      #defaultZone: http://localhost:6001/eureka
      # Eureka服务注册中心会将自己作为客户端来尝试注册它自己，必須禁止,则不会在eurekaserver中显示注册
    #register-with-eureka: false
    #fetch-registry: false
    #instance:
      #prefer-ip-address: true
      #instance-id: status-provider1



info:
  app.name: provider
  author: wjf
