server:
  port: 15000       #微服务端口


spring:
  application:
    name: studentInfoService-zxq #微服务名称
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源操作
    driver-class-name: com.mysql.jdbc.Driver #数据库的驱动mysql
    url: jdbc:mysql://localhost:3306/clouddemo?useUnicode=true&characterEncoding=utf-8&useSSL=false #数据库url,一定要有
    username: root  #数据库用户名密码
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml #spring与mybatis的整合，后续将会在resources文件夹下建立一个mapper文件夹，存放各种mapper.xml文件
  type-aliases-package: xiuqin.springcloud.entities    #所有entity实体类所在包

