#  不过实际上大部分都配置了datasource，最后仔细查找发现，
#  idea中创建的application文件类型为”yaml“！！！，
#  不过spring boot只能识别”yml“和”properties“，
#  导致无法读取到springboot配置文件中datasource内容，修改完成之后即可正常启动
server:
  port: 13000

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:9001/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: status-provider1
info:
  app.name: provider1-9091
  author: XingChao




spring:
  application:
    name: provider-zxc
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#  datasource:
#    name: gzst2020
#    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
#    druid:
      #监控统计拦截的filters
#      filters: stat
#      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
#      url: jdbc:mysql://localhost:3306/clouddemo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: 123456
      #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
      #获取连接等待超时时间
#      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zxc.grades.model  # 注意：对应实体类的路径